"""add purchase_date to positions

Revision ID: e46b80eaf586
Revises: 0002
Create Date: 2026-05-20 14:42:30.077209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e46b80eaf586'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sentiment_date'), table_name='sentiment_history')
    op.drop_index(op.f('ix_sentiment_ticker'), table_name='sentiment_history')
    op.drop_table('sentiment_history')
    op.drop_index(op.f('ix_ohlcv_date'), table_name='ohlcv_records')
    op.drop_index(op.f('ix_ohlcv_ticker'), table_name='ohlcv_records')
    op.create_index(op.f('ix_ohlcv_records_date'), 'ohlcv_records', ['date'], unique=False)
    op.create_index(op.f('ix_ohlcv_records_ticker'), 'ohlcv_records', ['ticker'], unique=False)
    op.drop_constraint(op.f('portfolios_user_id_key'), 'portfolios', type_='unique')
    op.drop_index(op.f('ix_portfolios_user_id'), table_name='portfolios')
    op.create_index(op.f('ix_portfolios_user_id'), 'portfolios', ['user_id'], unique=True)
    op.add_column('positions', sa.Column('purchase_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'purchase_date')
    op.drop_index(op.f('ix_portfolios_user_id'), table_name='portfolios')
    op.create_index(op.f('ix_portfolios_user_id'), 'portfolios', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('portfolios_user_id_key'), 'portfolios', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_ohlcv_records_ticker'), table_name='ohlcv_records')
    op.drop_index(op.f('ix_ohlcv_records_date'), table_name='ohlcv_records')
    op.create_index(op.f('ix_ohlcv_ticker'), 'ohlcv_records', ['ticker'], unique=False)
    op.create_index(op.f('ix_ohlcv_date'), 'ohlcv_records', ['date'], unique=False)
    op.create_table('sentiment_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('article_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('sentiment_history_pkey')),
    sa.UniqueConstraint('ticker', 'date', name=op.f('uq_sentiment_ticker_date'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_sentiment_ticker'), 'sentiment_history', ['ticker'], unique=False)
    op.create_index(op.f('ix_sentiment_date'), 'sentiment_history', ['date'], unique=False)
    # ### end Alembic commands ###
